// packages/vue-follow-button/example/src/App.vue
<template>
  <div id="app">
    <button v-if="!isConnected" @click="connectWallet">Connect Wallet</button>
    <h2 v-if="!!account">My Address: {{ account }}</h2>
    <h2 v-if="!!account">Target Address: 0xe6aab1f16ff560d309ed7ce8e08d290306a0906c</h2>
    <VueFollowButton
      v-if="isConnected"
      namespace="CyberConnect"
      toAddr="0xe6aab1f16ff560d309ed7ce8e08d290306a0906c"
      :provider="provider"
      :env="env"
      :chain="chain"
      @success="handleSuccess"
      @failure="handleFailure"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import Web3 from 'web3';
import {
  Env,
  Blockchain,
} from '@cyberlab/cyberconnect';
import { Config } from '@cyberlab/cyberconnect/lib/types';
import VueFollowButton from '@cyberconnect/vue-follow-button';

type Data = {
  account: Object | null,
  isConnected: boolean 
  env: Config['env'],
  chain: Config['chain'],
}

export default defineComponent({
  name: 'App',
  components: {
    VueFollowButton,
  },
  data(): Data {
    return {
      account: null,
      isConnected: false,
      env: Env.PRODUCTION,
      chain: Blockchain.ETH,
    };
  },
  computed: {
    provider() {
      return Web3.givenProvider;
    },
  },
  methods: {
    handleSuccess(e: any) {
      console.log(e);
    },
    handleFailure(e: any) {
      console.log(e);
    },
    async connectWallet() {
      if (typeof window.ethereum === 'undefined' || typeof window.ethereum.request === 'undefined') {
        console.error('MetaMask is not installed!');

        return;
      }

      const accounts = await window.ethereum.request({
        method: 'eth_requestAccounts',
      });

      this.account = accounts[0];
      this.isConnected = true;
    }
  }
});
</script>

// packages/react-follow-button/demo/src/App.tsx
import { useState } from "react";
import "./App.css";
import Web3 from "web3";
import {
  FollowButton,
  Env,
  Blockchain,
} from "@cyberconnect/react-follow-button";

function App() {
  const targetAddr = "0xe6aab1f16ff560d309ed7ce8e08d290306a0906c";
  const [account, setAccount] = useState<string>("");
  const [isWalletConnected, setIsWalletConnected] = useState<boolean>(false);

  const connectWallet = async () => {
    if (typeof window.ethereum === "undefined") {
      console.error("MetaMask is installed!");
    }
    const accounts = await window.ethereum.request({
      method: "eth_requestAccounts",
    });

    setAccount(accounts[0]);
    setIsWalletConnected(true);
  };

  return (
    <div className="App">
      {isWalletConnected ? (
        <div className="demo">
          <div className="address">
            <b>Account:</b> {account}
          </div>
          <div className="address">
            <b>Target:</b> {targetAddr}
          </div>
          <FollowButton
            provider={Web3.givenProvider}
            namespace="CyberConnect"
            toAddr={targetAddr}
            env={Env.PRODUCTION}
            chain={Blockchain.ETH}
            onSuccess={(e) => {
              console.log(e);
            }}
            onFailure={(e) => {
              console.log(e);
            }}
          />
        </div>
      ) : (
        <button className="connect-button" onClick={connectWallet}>
          Connect Wallet
        </button>
      )}
    </div>
  );
}

export default App;
